// Re-exports of Paraglide-generated i18n code.
// The actual files under `src/i18n/paraglide/` are generated by the
// @inlang/paraglide-js Vite plugin (see vite.config.ts) and are gitignored.
import * as m from "../i18n/paraglide/messages.js";
import {
  getLocale,
  setLocale,
  getTextDirection,
} from "../i18n/paraglide/runtime.js";

export { m, getLocale, setLocale, getTextDirection };